name: Build Unity

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'
        - 'deliverables/**'
        - 'Server/**'
        - 'Builds/**'
        - '.github/workflows/server_deploy.yml'

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    concurrency: 
      group: unity-build
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./Unity/CityBuilder
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        testMode:
          - ./Unity/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.0.0
        with:
          projectPath: ${{ matrix.projectPath }}
      - name: Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
